### ISSUE TITLE
Error : make scaffold

### ISSUE THREAD

**Issue by englianhu** [barraq/pandoc-moderncv#16]
I've follow the steps, but there is an issue when I gonna start create cv. I am using Linux Centos7. Related https://github.com/alanorth/cv/issues/4.

``` diff
$ make scaffold
make: *** No rule to make target `scaffold'.  Stop.
```

**Comment by barraq** [comment]
Hi @englianhu did you really follow these steps:

```
$ git clone https://github.com/barraq/pandoc-moderncv.git
$ cd pandoc-moderncv/
$ make scaffold
```

It looks like you are running the make command under the wrong path. The error you get is like doing:

```
$ make something
make: *** No rule to make target 'something'.  Stop.
```

**Comment by englianhu** [comment]
Found the path prior to run `$git`, Resolved and thanks lot.

``` r
> getwd()
[1] "/home/ryoeng/Scibrokes/Owner.git"
```
