### ISSUE TITLE
Sass error on 'make html'

### ISSUE THREAD

**Issue by offlinemark** [barraq/pandoc-moderncv#5]
I get this error message upon running 'make html':

```
$ make html
mkdir build
mkdir dist
rsync -rupE fonts dist
rsync -rupE cv/images dist
compass compile \
      --require susy \
      --sass-dir stylesheets \
      --javascripts-dir javascripts \
      --css-dir dist/stylesheets \
      --image-dir cv/images \
      stylesheets/style.scss
directory dist/stylesheets/
    error stylesheets/style.scss (Line 17: Mixin container takes 1 argument but 6 were passed.)
   create dist/stylesheets/style.css
make: *** [style] Error 1
```

If I run 'make html' again, the error does not appear, but the cv.html file does not have CSS and has the sass error message at the top.

Gem list:

```
$ gem list
*** LOCAL GEMS ***

bigdecimal (1.2.0)
CFPropertyList (2.2.0)
chunky_png (1.3.1)
compass (1.0.0.alpha.20)
compass-core (1.0.0.alpha.20)
compass-import-once (1.0.4)
ffi (1.9.3)
fssm (0.2.10)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
mime-types (2.0)
minitest (4.3.2)
multi_json (1.10.1)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.0.0)
sass (3.3.9, 3.2.19)
sqlite3 (1.3.7)
susy (2.1.2)
test-unit (2.0.0.0)
```

I had to do 'gem install compass --pre' to fix sass version conflict error messages originally when I ran 'make html'. Is there any more info you need?

**Comment by offlinemark** [comment]
Also, this is the offending line in `stylesheets/style.scss`:

```
@include container($total-columns, $xs-layout, $sm-layout, $md-layout, $lg-layout, $wd-layout);
```

**Comment by barraq** [comment]
Hi @mossberg thanks for pointing that out. In fact the problem comes from the fact that Susy was upgraded from 1.x to 2.x and that they are many changes with 2.x. As I see you have 2.1.2 installed. When I did the Stylesheet Susy 2.x was still in beta... I'll patch the Stylesheet to make it work with Susy 2.x and deprecate 1.x.

I keep you posted.
Thanks
