### ISSUE TITLE
Create page break in PDF

### ISSUE THREAD

**Issue by juranta** [barraq/pandoc-moderncv#6]
I started to create a cv based on these styles and technique. However, my cv ended up such that it looked a bit "unprofessional" because in the end of one page there was just a title and one line of text, which continued in the next page. I wanted to create a page break so that the title would start in the next page. I don't know much about CSS or generating PDFs, but after some experimentation I found one solution which worked. In `style.scss` I inserted this:

```
@media print {
    .page-breaker { display: block; page-break-before: always;}
}
```

It's possible to insert HTML in a Markdown file, so in my Markdown cv I inserted this:

```
## Section 1

Some text.

</section>
   <div class="page-breaker"></div>
<section>

## Section 2

More text.
```

It seems to work. That page break div didn't work inside "sections", so I had to close and start a section in that snippet. Does anyone know if there's a prettier way to create a page break in pdf?

**Comment by barraq** [comment]
Hi @juranta in Pandoc-ModernCV the PDF output is generated by printing the HTML output with the help of wkpdf or wkhtmltopdf (depending on your platform), as follow you should look at how to put a page break in HTML.

Regarding the page break, it is not really clean to put HTML code inside your markdown file.
Instead I suggest you to use the Pandoc _header_attributes_ extension which allow you to add custom classes and ids to your headers. Looking at your updated SCSS;

``` css
@media print {
    .page-breaker { display: block; page-break-before: always;}
}
```

what  you can do is simply:

``` markdown
...
Some content here.
The page break will appear just before the next header.

## Some Title {.page-breaker}
Some content
...
```

Does this helps?

**Comment by juranta** [comment]
Thanks for pointing out to the _header_attributes_ extension in Pandoc. It worked in the sense that the generated HTML got properly modified:

```
  </section>
  <section id="my_section" class="level2 page-breaker">
```

However, this does not create a page break in PDF. To create a page break, I need something like this:

```
  </section>
  <div class="page-breaker"/>
  <section id="my_section" class="level2">
```

That is, that page-breaker class doesn't work in a `section`, but in a `div` between sections it works. I'll see if I can get it work with sections.

[This page](http://www.w3schools.com/cssref/pr_print_pagebb.asp) says: 

> "Note: You cannot use this property on an empty `div` or on absolutely positioned elements."

For me, it's exactly an empty `div` where it works as long as it's not inside a `section`. Hmm...

**Comment by tuxinaut** [comment]
If i use the page-breaker class with a section it don't work. The empty div solution form @juranta works well. But how can i create the divs without edit the generated html by hand.
